// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("rescript/lib/js/pervasives.js");

function getItemIndicators(arg) {
  return Pervasives.failwith("unimplemented");
}

exports.getItemIndicators = getItemIndicators;
/* No side effect */
